TRUNCATE TABLE [dbo].[Provinces]
TRUNCATE TABLE [dbo].[Cantons]
TRUNCATE TABLE [dbo].[Districts]

INSERT INTO [dbo].[Provinces] ([Name],[Active]) 
VALUES 
	('San José', 1),
	('Alajuela', 1),
	('Cartago', 1),
	('Heredia', 1),
	('Guanacaste', 1),
	('Puntarenas', 1),
	('Limon', 1)


INSERT INTO [dbo].[Cantons] ([ProvinceId], [Name], [Active]) 
VALUES
	(1, 'San José', 1),
	(1, 'Escazú', 1),
	(1, 'Desamparados', 1),
	(1, 'Puriscal', 1),  
	(1, 'Tarrazú', 1),  
	(1, 'Aserrí', 1),  
	(1, 'Mora', 1),  
	(1, 'Goicoechea', 1),  
	(1, 'Santa Ana', 1),  
	(1, 'Alajuelita', 1),  
	(1, 'Vásquez de Coronado', 1),  
	(1, 'Acosta', 1), 
	(1, 'Tibás', 1),
	(1, 'Moravia', 1),
	(1, 'Montes de Oca', 1),
	(1, 'Turrubares', 1),
	(1, 'Dota', 1),
	(1, 'Curridabat', 1),
	(1, 'Pérez Zeledón', 1),
	(1, 'León Cortés Castro', 1),
	(2, 'Alajuela', 1),
	(2, 'San Ramón', 1),
	(2, 'Grecia', 1),
	(2, 'San Mateo', 1),
	(2, 'Atenas', 1),
	(2, 'Naranjo', 1),
	(2, 'Palmares', 1),
	(2, 'Poás', 1),
	(2, 'Orotina', 1),
	(2, 'San Carlos', 1),
	(2, 'Zarcero', 1),
	(2, 'Valverde Vega', 1),
	(2, 'Upala', 1),
	(2, 'Los Chiles', 1),
	(2, 'Guatuso', 1),
	(2, 'Río Cuarto', 1),
	(3, 'Cartago', 1),
	(3, 'Paraíso', 1),
	(3, 'La Unión', 1),
	(3, 'Jiménez', 1),
	(3, 'Turrialba', 1),
	(3, 'Alvarado', 1),
	(3, 'Oreamuno', 1),
	(3, 'El Guarco', 1),
	(4, 'Heredia', 1),
	(4, 'Barva', 1),
	(4, 'Santo Domingo', 1),
	(4, 'Santa Bárbara', 1),
	(4, 'San Rafael', 1),
	(4, 'San Isidro', 1),
	(4, 'Belén', 1),
	(4, 'Flores', 1),
	(4, 'San Pablo', 1),
	(4, 'Sarapiquí', 1),
	(5, 'Liberia', 1),
	(5, 'Nicoya', 1),
	(5, 'Santa Cruz', 1),
	(5, 'Bagaces', 1),
	(5, 'Carrillo', 1),
	(5, 'Cañas', 1),  
	(5, 'Abangares', 1),  
	(5, 'Tilarán', 1),  
	(5, 'Nandayure', 1),  
	(5, 'La Cruz', 1),  
	(5, 'Hojancha', 1),  
	(6, 'Puntarenas', 1),  
	(6, 'Esparza', 1),
	(6, 'Buenos Aires', 1),
	(6, 'Montes de Oro', 1),
	(6, 'Osa', 1),
	(6, 'Quepos', 1),
	(6, 'Golfito', 1),
	(6, 'Coto Brus', 1),
	(6, 'Parrita', 1),
	(6, 'Corredores', 1),
	(6, 'Garabito', 1),
	(7, 'Limón', 1),
	(7, 'Pococí', 1),
	(7, 'Siquirres', 1),
	(7, 'Talamanca', 1),
	(7, 'Matina', 1),
	(7, 'Guácimo', 1)

INSERT INTO [dbo].[Districts] ([CantonId], [Name], [Active]) 
VALUES 
	((SELECT [Id] FROM [dbo].[Cantons] WHERE [Name] = 'San José'), 'Carmen', 1),
	((SELECT [Id] FROM [dbo].[Cantons] WHERE [Name] = 'San José'), 'Merced', 1),
	((SELECT [Id] FROM [dbo].[Cantons] WHERE [Name] = 'San José'), 'Hospital', 1),
	((SELECT [Id] FROM [dbo].[Cantons] WHERE [Name] = 'San José'), 'Catedral', 1),
	((SELECT [Id] FROM [dbo].[Cantons] WHERE [Name] = 'San José'), 'Zapote', 1),
	((SELECT [Id] FROM [dbo].[Cantons] WHERE [Name] = 'San José'), 'San Francisco de Dos Ríos', 1),
	((SELECT [Id] FROM [dbo].[Cantons] WHERE [Name] = 'San José'), 'Uruca', 1),
	((SELECT [Id] FROM [dbo].[Cantons] WHERE [Name] = 'San José'), 'Mata Redonda', 1),
	((SELECT [Id] FROM [dbo].[Cantons] WHERE [Name] = 'San José'), 'Pavas', 1),
	((SELECT [Id] FROM [dbo].[Cantons] WHERE [Name] = 'San José'), 'Hatillo', 1),
	((SELECT [Id] FROM [dbo].[Cantons] WHERE [Name] = 'San José'), 'San Sebastián', 1),
	((SELECT [Id] FROM [dbo].[Cantons] WHERE [Name] = 'Escazú'), 'Escazú', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Escazú'), 'San Antonio', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Escazú'), 'San Rafael', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Desamparados'), 'Desamparados', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Desamparados'), 'San Miguel', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Desamparados'), 'San Juan de Dios', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Desamparados'), 'San Rafael Arriba', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Desamparados'), 'San Antonio', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Desamparados'), 'Frailes', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Desamparados'), 'Patarrá', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Desamparados'), 'San Cristóbal', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Desamparados'), 'Rosario', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Desamparados'), 'Damas', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Desamparados'), 'San Rafael Abajo', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Desamparados'), 'Gravilias', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Desamparados'), 'Los Guido', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Puriscal'), 'Santiago', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Puriscal'), 'Mercedes Sur', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Puriscal'), 'Barbacoas', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Puriscal'), 'Grifo Alto', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Puriscal'), 'San Rafael', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Puriscal'), 'Candelarita', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Puriscal'), 'Desamparaditos', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Puriscal'), 'San Antonio', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Puriscal'), 'Chires', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Tarrazú'), 'San Marcos', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Tarrazú'), 'San Lorenzo', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Tarrazú'), 'San Carlos', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Aserrí'), 'Aserrí', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Aserrí'), 'Tarbaca', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Aserrí'), 'Vuelta de Jorco', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Aserrí'), 'San Gabriel', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Aserrí'), 'Legua', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Aserrí'), 'Monterrey', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Aserrí'), 'Salitrillos', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Mora'), 'Colón', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Mora'), 'Guayabo', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Mora'), 'Tabarcia', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Mora'), 'Piedras Negras', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Mora'), 'Picagres', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Mora'), 'Jaris', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Mora'), 'Quitirrisí', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Goicoechea'), 'Guadalupe', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Goicoechea'), 'San Francisco', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Goicoechea'), 'Calle Blancos', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Goicoechea'), 'Mata de Plátano', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Goicoechea'), 'Ipís', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Goicoechea'), 'Rancho Redondo', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Goicoechea'), 'Purral', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Santa Ana'), 'Santa Ana', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Santa Ana'), 'Salitral', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Santa Ana'), 'Pozos', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Santa Ana'), 'Uruca', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Santa Ana'), 'Piedades', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Santa Ana'), 'Brasil', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Alajuelita'), 'Alajuelita', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Alajuelita'), 'San Josecito', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Alajuelita'), 'San Antonio', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Alajuelita'), 'Concepción', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Alajuelita'), 'San Felipe', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Vásquez de Coronado'), 'San Isidro', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Vásquez de Coronado'), 'San Rafael', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Vásquez de Coronado'), 'Dulce Nombre de Jesús', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Vásquez de Coronado'), 'Patalillo', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Vásquez de Coronado'), 'Cascajal', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Acosta'), 'San Ignacio', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Acosta'), 'Guaitil', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Acosta'), 'Palmichal', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Acosta'), 'Cangrejal', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Acosta'), 'Sabanillas', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Tibás'), 'San Juan', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Tibás'), 'Cinco Esquinas', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Tibás'), 'Anselmo Llorente', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Tibás'), 'León XIII', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Tibás'), 'Colima', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Moravia'), 'San Vicente', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Moravia'), 'San Jerónimo', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Moravia'), 'La Trinidad', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Montes de Oca'), 'San Pedro', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Montes de Oca'), 'Sabanilla', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Montes de Oca'), 'Mercedes', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Montes de Oca'), 'San Rafael', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Turrubares'), 'San Pablo', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Turrubares'), 'San Pedro', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Turrubares'), 'San Juan de Mata', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Turrubares'), 'San Luis', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Turrubares'), 'Carara', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Dota'), 'Santa María', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Dota'), 'Jardín', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Dota'), 'Copey', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Curridabat'), 'Curridabat', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Curridabat'), 'Granadilla', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Curridabat'), 'Sánchez', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Curridabat'), 'Tirrases', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Pérez Zeledón'), 'San Isidro de El General', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Pérez Zeledón'), 'El General', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Pérez Zeledón'), 'Daniel Flores', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Pérez Zeledón'), 'Rivas', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Pérez Zeledón'), 'San Pedro', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Pérez Zeledón'), 'Platanares', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Pérez Zeledón'), 'Pejibaye', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Pérez Zeledón'), 'Cajón', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Pérez Zeledón'), 'Barú', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Pérez Zeledón'), 'Río Nuevo', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Pérez Zeledón'), 'Páramo', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Pérez Zeledón'), 'La Amistad', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'León Cortés Castro'), 'San Pablo', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'León Cortés Castro'), 'San Andrés', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'León Cortés Castro'), 'Llano Bonito', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'León Cortés Castro'), 'San Isidro', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'León Cortés Castro'), 'Santa Cruz', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'León Cortés Castro'), 'San Antonio', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Alajuela'), 'Alajuela', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Alajuela'), 'San José', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Alajuela'), 'Carrizal', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Alajuela'), 'San Antonio', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Alajuela'), 'Guácima', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Alajuela'), 'San Isidro', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Alajuela'), 'Sabanilla', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Alajuela'), 'San Rafael', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Alajuela'), 'Río Segundo', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Alajuela'), 'Desamparados', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Alajuela'), 'Turrúcares', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Alajuela'), 'Tambor', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Alajuela'), 'Garita', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Alajuela'), 'Sarapiquí', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'San Ramón'), 'San Ramón', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'San Ramón'), 'Santiago', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'San Ramón'), 'San Juan', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'San Ramón'), 'Piedades Norte', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'San Ramón'), 'Piedades Sur', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'San Ramón'), 'San Rafael', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'San Ramón'), 'San Isidro', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'San Ramón'), 'Los Ángeles', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'San Ramón'), 'Alfaro', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'San Ramón'), 'Volio', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'San Ramón'), 'Concepción', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'San Ramón'), 'Zapotal', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'San Ramón'), 'Peñas Blancas', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'San Ramón'), 'San Lorenzo', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Grecia'), 'Grecia', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Grecia'), 'San Isidro', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Grecia'), 'San José', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Grecia'), 'San Roque', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Grecia'), 'Tacares', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Grecia'), 'Río Cuarto', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Grecia'), 'Puente de Piedra', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Grecia'), 'Bolívar', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'San Mateo'), 'San Mateo', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'San Mateo'), 'Desmonte', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'San Mateo'), 'Jesús María', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'San Mateo'), 'Labrador', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Atenas'), 'Atenas', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Atenas'), 'Jesús', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Atenas'), 'Mercedes', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Atenas'), 'San Isidro', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Atenas'), 'Concepción', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Atenas'), 'San José', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Atenas'), 'Santa Eulalia', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Atenas'), 'Escobal', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Naranjo'), 'Naranjo', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Naranjo'), 'San Miguel', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Naranjo'), 'San José', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Naranjo'), 'Cirrí Sur', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Naranjo'), 'San Jerónimo', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Naranjo'), 'San Juan', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Naranjo'), 'El Rosario', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Naranjo'), 'Palmitos', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Palmares'), 'Palmares', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Palmares'), 'Zaragoza', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Palmares'), 'Buenos Aires', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Palmares'), 'Santiago', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Palmares'), 'Candelaria', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Palmares'), 'Esquipulas', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Palmares'), 'La Granja', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Poás'), 'San Pedro', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Poás'), 'San Juan', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Poás'), 'San Rafael', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Poás'), 'Carrillos', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Poás'), 'Sabana Redonda', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Orotina'), 'Orotina', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Orotina'), 'El Mastate', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Orotina'), 'Hacienda Vieja', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Orotina'), 'Coyolar', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Orotina'), 'La Ceiba', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'San Carlos'), 'Quesada', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'San Carlos'), 'Florencia', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'San Carlos'), 'Buenavista', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'San Carlos'), 'Aguas Zarcas', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'San Carlos'), 'Venecia', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'San Carlos'), 'Pital', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'San Carlos'), 'La Fortuna', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'San Carlos'), 'La Tigra', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'San Carlos'), 'La Palmera', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'San Carlos'), 'Venado', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'San Carlos'), 'Cutris', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'San Carlos'), 'Monterrey', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'San Carlos'), 'Pocosol', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Zarcero'), 'Zarcero', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Zarcero'), 'Laguna', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Zarcero'), 'Tapezco', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Zarcero'), 'Guadalupe', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Zarcero'), 'Palmira', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Zarcero'), 'Zapote', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Zarcero'), 'Brisas', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Valverde Vega'), 'Sarchí Norte', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Valverde Vega'), 'Sarchí Sur', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Valverde Vega'), 'Toro Amarillo', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Valverde Vega'), 'San Pedro', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Valverde Vega'), 'Rodríguez', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Upala'), 'Upala', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Upala'), 'Aguas Claras', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Upala'), 'San José o Pizote', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Upala'), 'Bijagua', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Upala'), 'Delicias', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Upala'), 'Dos Ríos', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Upala'), 'Yolillal', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Upala'), 'Canalete', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Los Chiles'), 'Los Chiles', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Los Chiles'), 'Caño Negro', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Los Chiles'), 'El Amparo', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Los Chiles'), 'San Jorge', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Guatuso'), 'San Rafael', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Guatuso'), 'Buenavista', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Guatuso'), 'Cote', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Guatuso'), 'Katira', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Río Cuarto'), 'Río Cuarto', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Cartago'), 'Oriental', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Cartago'), 'Occidental', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Cartago'), 'Carmen', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Cartago'), 'San Nicolás', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Cartago'), 'Aguacaliente o San Francisco', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Cartago'), 'Guadalupe o Arenilla', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Cartago'), 'Corralillo', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Cartago'), 'Tierra Blanca', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Cartago'), 'Dulce Nombre', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Cartago'), 'Llano Grande', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Cartago'), 'Quebradilla', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Paraíso'), 'Paraíso', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Paraíso'), 'Santiago', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Paraíso'), 'Orosi', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Paraíso'), 'Cachí', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Paraíso'), 'Llanos de Santa Lucía', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'La Unión'), 'Tres Ríos', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'La Unión'), 'San Diego', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'La Unión'), 'San Juan', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'La Unión'), 'San Rafael', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'La Unión'), 'Concepción', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'La Unión'), 'Dulce Nombre', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'La Unión'), 'San Ramón', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'La Unión'), 'Río Azul', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Jiménez'), 'Juan Viñas', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Jiménez'), 'Tucurrique', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Jiménez'), 'Pejibaye', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Turrialba'), 'Turrialba', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Turrialba'), 'La Suiza', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Turrialba'), 'Peralta', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Turrialba'), 'Santa Cruz', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Turrialba'), 'Santa Teresita', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Turrialba'), 'Pavones', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Turrialba'), 'Tuis', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Turrialba'), 'Tayutic', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Turrialba'), 'Santa Rosa', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Turrialba'), 'Tres Equis', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Turrialba'), 'La Isabel', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Turrialba'), 'Chirripó', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Alvarado'), 'Pacayas', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Alvarado'), 'Cervantes', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Alvarado'), 'Capellades', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Oreamuno'), 'San Rafael', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Oreamuno'), 'Cot', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Oreamuno'), 'Potrero Cerrado', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Oreamuno'), 'Cipreses', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Oreamuno'), 'Santa Rosa', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'El Guarco'), 'Tejar', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'El Guarco'), 'San Isidro', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'El Guarco'), 'Tobosi', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'El Guarco'), 'Patio de Agua', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Heredia'), 'Heredia', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Heredia'), 'Mercedes', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Heredia'), 'San Francisco', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Heredia'), 'Ulloa', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Heredia'), 'Varablanca', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Barva'), 'Barva', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Barva'), 'San Pedro', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Barva'), 'San Pablo', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Barva'), 'San Roque', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Barva'), 'Santa Lucía', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Barva'), 'San José de la Montaña', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Santo Domingo'), 'Santo Domingo', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Santo Domingo'), 'San Vicente', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Santo Domingo'), 'San Miguel', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Santo Domingo'), 'Paracito', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Santo Domingo'), 'Santo Tomás', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Santo Domingo'), 'Santa Rosa', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Santo Domingo'), 'Tures', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Santo Domingo'), 'Para', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Santa Bárbara'), 'Santa Bárbara', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Santa Bárbara'), 'San Pedro', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Santa Bárbara'), 'San Juan', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Santa Bárbara'), 'Jesús', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Santa Bárbara'), 'Santo Domingo', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Santa Bárbara'), 'Puraba', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'San Rafael'), 'San Rafael', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'San Rafael'), 'San Josécito', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'San Rafael'), 'Santiago', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'San Rafael'), 'Ángeles', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'San Rafael'), 'Concepción', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'San Isidro'), 'San Isidro', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'San Isidro'), 'San José', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'San Isidro'), 'Concepción', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'San Isidro'), 'San Francisco', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Belén'), 'San Antonio', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Belén'), 'La Ribera', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Belén'), 'La Asunción', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Flores'), 'San Joaquín', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Flores'), 'Barrantes', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Flores'), 'Llorente', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'San Pablo'), 'San Pablo', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'San Pablo'), 'Rincón de Sabanilla', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Sarapiquí'), 'Puerto Viejo', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Sarapiquí'), 'La Virgen', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Sarapiquí'), 'Horquetas', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Sarapiquí'), 'Llanuras del Gaspar', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Sarapiquí'), 'Cureña', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Liberia'), 'Liberia', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Liberia'), 'Cañas Dulces', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Liberia'), 'Mayorga', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Liberia'), 'Nacascolo', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Liberia'), 'Curubandé', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Nicoya'), 'Nicoya', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Nicoya'), 'Mansión', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Nicoya'), 'San Antonio', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Nicoya'), 'Quebrada Honda', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Nicoya'), 'Sámara', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Nicoya'), 'Nosara', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Nicoya'), 'Belén de Nosarita', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Santa Cruz'), 'Santa Cruz', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Santa Cruz'), 'Bolsón', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Santa Cruz'), 'Veintisiete de Abril', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Santa Cruz'), 'Tempate', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Santa Cruz'), 'Cartagena', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Santa Cruz'), 'Cuajiniquil', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Santa Cruz'), 'Diria', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Santa Cruz'), 'Cabo Velas', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Santa Cruz'), 'Tamarindo', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Bagaces'), 'Bagaces', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Bagaces'), 'Fortuna', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Bagaces'), 'Mogote', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Bagaces'), 'Río Naranjo', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Carrillo'), 'Filadelfia', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Carrillo'), 'Palmira', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Carrillo'), 'Sardinal', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Carrillo'), 'Belén', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Cañas'), 'Cañas', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Cañas'), 'Palmira', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Cañas'), 'San Miguel', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Cañas'), 'Bebedero', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Cañas'), 'Porozal', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Abangares'), 'Juntas', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Abangares'), 'Sierra', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Abangares'), 'San Juan', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Abangares'), 'Colorado', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Tilarán'), 'Tilarán', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Tilarán'), 'Quebrada Grande', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Tilarán'), 'Tronadora', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Tilarán'), 'Santa Rosa', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Tilarán'), 'Líbano', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Tilarán'), 'Tierras Morenas', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Tilarán'), 'Arenal', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Nandayure'), 'Carmona', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Nandayure'), 'Santa Rita', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Nandayure'), 'Zapotal', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Nandayure'), 'San Pablo', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Nandayure'), 'Porvenir', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Nandayure'), 'Bejuco', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'La Cruz'), 'La Cruz', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'La Cruz'), 'Santa Cecilia', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'La Cruz'), 'Garita', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'La Cruz'), 'Santa Elena', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Hojancha'), 'Hojancha', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Hojancha'), 'Monte Romo', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Hojancha'), 'Puerto Carrillo', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Hojancha'), 'Huacas', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Puntarenas'), 'Puntarenas', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Puntarenas'), 'Pitahaya', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Puntarenas'), 'Chomes', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Puntarenas'), 'Lepanto', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Puntarenas'), 'Paquera', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Puntarenas'), 'Manzanillo', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Puntarenas'), 'Guacimal', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Puntarenas'), 'Barranca', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Puntarenas'), 'Monte Verde', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Puntarenas'), 'Isla del Coco', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Puntarenas'), 'Cobano', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Puntarenas'), 'Chacarita', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Puntarenas'), 'Chira', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Puntarenas'), 'Acapulco', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Puntarenas'), 'El Roble', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Puntarenas'), 'Arancibia', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Esparza'), 'Espíritu Santo', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Esparza'), 'San Juan Grande', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Esparza'), 'Macacona', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Esparza'), 'San Rafael', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Esparza'), 'San Jerónimo', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Esparza'), 'Caldera', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Buenos Aires'), 'Buenos Aires', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Buenos Aires'), 'Volcan', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Buenos Aires'), 'Potrero Grande', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Buenos Aires'), 'Boruca', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Buenos Aires'), 'Pilas', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Buenos Aires'), 'Colinas', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Buenos Aires'), 'Changena', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Buenos Aires'), 'Briolley', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Buenos Aires'), 'Brunka', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Montes de Oro'), 'Miramar', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Montes de Oro'), 'La Unión', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Montes de Oro'), 'San Isidro', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Osa'), 'Puerto Cortés', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Osa'), 'Palmar', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Osa'), 'Sierpe', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Osa'), 'Bahia Ballena', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Osa'), 'Piedras Blancas', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Osa'), 'Bahía Drake', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Quepos'), 'Quepos', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Quepos'), 'Savegre', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Quepos'), 'Naranjito', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Golfito'), 'Golfito', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Golfito'), 'Puerto Jiménez', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Golfito'), 'Guaycará', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Golfito'), 'Pavón', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Coto Brus'), 'San Vito', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Coto Brus'), 'Sabalito', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Coto Brus'), 'Aguabuena', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Coto Brus'), 'Limóncito', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Coto Brus'), 'Pittier', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Coto Brus'), 'Gutiérrez Braun', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Parrita'), 'Parrita', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Corredores'), 'Corredor', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Corredores'), 'La Cuesta', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Corredores'), 'Canoas', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Corredores'), 'Laurel', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Garabito'), 'Jacó', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Garabito'), 'Tarcoles', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Limón'), 'Limón', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Limón'), 'Valle La Estrella', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Limón'), 'Río Blanco', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Limón'), 'Matama', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Pococí'), 'Guápiles', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Pococí'), 'Jiménez', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Pococí'), 'La Rita', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Pococí'), 'Roxana', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Pococí'), 'Cariari', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Pococí'), 'Colorado', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Pococí'), 'La Colonia', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Siquirres'), 'Siquirres', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Siquirres'), 'Pacuarito', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Siquirres'), 'Florida', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Siquirres'), 'Germania', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Siquirres'), 'Cairo', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Siquirres'), 'Alegría', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Talamanca'), 'Bratsi', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Talamanca'), 'Sixaola', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Talamanca'), 'Cahuita', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Talamanca'), 'Telire', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Matina'), 'Matina', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Matina'), 'Batán', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Matina'), 'Carrandi', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Guácimo'), 'Guácimo', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Guácimo'), 'Mercedes', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Guácimo'), 'Pocora', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Guácimo'), 'Río Jiménez', 1),
	((SELECT [ID] FROM [dbo].[Cantons] WHERE [Name] = 'Guácimo'), 'Duacarí', 1)