CREATE TABLE [dbo].[UserBalances]
(
	[Id] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[UserId] INT NOT NULL,
	[Balance] DECIMAL(10,2) NOT NULL DEFAULT 0,
	[DateCreated] DATETIME NOT NULL DEFAULT GETDATE(),
	[DateUpdated] DATETIME NULL,
	[CreatedBy] INT NOT NULL,
	[UpdatedBy] INT NULL
)
